  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

 # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 2.0, i: 0.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 2.0, i: 0.0, d: 0.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 2.0, i: 0.0, d: 0.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 2.0, i: 0.0, d: 0.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 2.0, i: 0.0, d: 0.0}


